name: platos_cochabamba
version: 1.0.0+1

description: "Aplicación de platos típicos de Cochabamba"
publish_to: "none"

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  flutter_dotenv: ^5.0.2
  carousel_slider: ^5.1.1
  cached_network_image: ^3.2.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/silpancho.jpg
    - assets/pique macho.jpg
    - assets/chicharron.jpg
    - assets/sopa mani.jpg
